CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(50) NOT NULL,
	username VARCHAR(50) NOT NULL,

	UNIQUE(username)
);

CREATE TABLE IF NOT EXISTS rooms (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(50) NOT NULL,

	UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS messages (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	roomId INTEGER NOT NULL,
	userId INTEGER NOT NULL,
	message VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),

	CONSTRAINT fk_message_roomId 
		FOREIGN KEY(roomId)
			REFERENCES rooms(id),
	CONSTRAINT fk_message_userId
		FOREIGN KEY(userId)
			REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_message_createdAt ON messages (createdAt);
